- README.md
- examples/pgw/pgw.go
- examples/sgw/main.go
- examples/sgw/sgw.go
- v1/README.md
- v1/relay.go
- v1/u-conn.go
To forward GTPv1-U packet more efficiently(=faster, fewer resource consumption), add `RelayTo()` method to `*v1.UPlaneConn`.
This deprecates `Relay`, which was too bad at forwarding many packets.
> Improve U-Plane forwarding efficiency in v1-U

- examples/sgw/main.go
- examples/sgw/s5.go
- examples/sgw/sgw.go
- v1/README.md
- v2/conn.go
- v2/session.go
Add `PassMessageTo()` and `WaitMessage()` to send/receive messages targeted to specific session.
This is expected to be used in the nodes that has multiple GTP interfaces like S-GW.
> Improved session handling in S-GW

- examples/sgw/main.go
- examples/sgw/s11.go
- examples/sgw/s5.go
- v2/conn.go
- v2/constants.go
- v2/session.go
Now `examples/sgw` can handle Delete Bearer Request/Response.
This PR also contains some helpers to handle bearers easier.
> Add Delete Bearer Request/Response support for S-GW

- v1/tunnel.go
- v1/u-conn.go
- v2/session.go
Implemented some APIs to handle Linux Kernel GTP-U via netlink with [vishvananda/netlink](https://github.com/vishvananda/netlink). Userland GTP-U encap/decap/forwarding is still available for non-Linux users.
> Add support for Linux Kernel GTP-U in v1 package

- v0/ies/ie.go
- v1/ies/ie.go
- v1/tunnel.go
- v2/ies/paa.go
Fixed the following issues.
```
$ GOLANGCI_COM_RUN=1 golangci-lint run --out-format=json --issues-exit-code=0 --deadline=5m --new=false --new-from-rev= --new-from-patch=
v1/ies/ie.go:365: `newUint16ValIE` is unused (deadcode)
v0/ies/ie.go:236: `newStringIE` is unused (deadcode)
v2/ies/paa.go:14: `pdnTypeIPv4v6` is unused (deadcode)
v1/tunnel.go:38: Error return value of `netlink.GTPPDPDel` is not checked (errcheck)
v1/tunnel.go:41: Error return value of `netlink.GTPPDPDel` is not checked (errcheck)
```
> Make golangci happy

- README.md
Fix a URL link to examples directory in README.md.
Before: https://github.com/wmnsk/go-gtp/blob/master/gtp/examples
-> Shows a 404 error.
After: https://github.com/wmnsk/go-gtp/blob/master/examples
-> Shows a right examples page.
> Fix a URL link to examples in README

- examples/mme/main.go
- examples/mme/mme.go
- examples/mme/mock.go
- examples/pgw/pgw.go
- examples/sgw/s11.go
- examples/sgw/s5.go
- v2/conn.go
- v2/errors.go
- v2/helpers_test.go
- v2/session.go
Sessions(TEIDs) should be associated with peer address but it wasn't.
* add checks of peer's address matches or not when looking up
* fix timing issue that might happen in PassMessage / WaitMessage funcs
> Fixed bugs in session handling

- examples/mme/main.go
- examples/mme/mock.go
- examples/sgw/s11.go
- examples/sgw/s5.go
- v2/bearer.go
- v2/conn.go
- v2/helpers_test.go
- v2/session.go
* store peer nodes' address as a string to avoid calling String() every time looking up Session by TEID
https://gist.github.com/wmnsk/1de79b7cc1852c3020596f5f0f3a04fb
```
BenchmarkAddrComparisonString1-2         4453245               241 ns/op
BenchmarkAddrComparisonString2-2        360841701                3.17 ns/op
BenchmarkAddrComparisonBytes-2          286502511                4.12 ns/op
BenchmarkAddrComparisonReflect-2          639075              1600 ns/op
```
* ... to be updated?
> Performance improvements for GTPv2

- v2/conn.go
- v2/logger.go
Implemented logging to provide subtle information to users.
It never prints important messages that asks users to take any actions, but just shares the small things background goroutines find.
> Implement logger in v2 package

- v2/conn.go
In the case that the peer responds to CreateSessionRequest very fast, Conn might not have registered the session created by CreateSession() method. This does not seem to happen in the most cases, as responders normally has some things to do before response and it would not be so fast, though.
This fixes ensures that the created session is registered before sending CreateSessionRequest to avoid such cases.
> Fix CreateSession() for super-fast response

- examples/gw-tester/enb/enb.go
- examples/gw-tester/pgw/main.go
- examples/gw-tester/pgw/pgw.go
- examples/gw-tester/sgw/main.go
- examples/gw-tester/sgw/sgw.go
- examples/mme/main.go
- examples/mme/mock.go
- examples/pgw/main.go
- examples/pgw/pgw.go
- examples/sgw/main.go
- v1/README.md
- v1/logger.go
- v1/relay_test.go
- v1/tunnel_linux.go
- v1/u-conn.go
- v1/u-conn_test.go
**This contains big changes of exported API**
> Context-based conn handling for GTPv1-U

- examples/mme/main.go
- examples/pgw/main.go
- examples/sgw/main.go
- v2/conn.go
- v2/conn_test.go
- v2/helpers_test.go
This PR addresses #62 
The number of places session lookup touches is quite a bit. Things i am fuzzy around -
- There is nothing to connect Session and the Conn, so we have to pass TEIDSessionMap OR we can add to Session struct (needed in NewSession)
- TEID being unique per Conn (this PR) vs Conn+IfType (existing impl)
- Need for mutexes around sync.Map
- Test changes made
> Session add/lookup using sync map

- v2/helpers_test.go
Using the concept of sub-benchmarks we can collapse all the cases into a for loop.
```
goos: linux
goarch: amd64
pkg: github.com/wmnsk/go-gtp/v2
BenchmarkAddSession/1-88  	   97202	     12358 ns/op	   17240 B/op	      20 allocs/op
BenchmarkAddSession/10-88 	   95139	     12411 ns/op	   17240 B/op	      20 allocs/op
BenchmarkAddSession/100-88         	   92438	     12841 ns/op	   17240 B/op	      20 allocs/op
BenchmarkAddSession/1000-88        	   99679	     10672 ns/op	   17240 B/op	      20 allocs/op
BenchmarkAddSession/10000-88       	  194298	      9588 ns/op	   17240 B/op	      20 allocs/op
BenchmarkAddSession/100000-88      	  306838	      7576 ns/op	   17240 B/op	      20 allocs/op
PASS
ok  	github.com/wmnsk/go-gtp/v2	12.070s
Success: Benchmarks passed.
```
Signed-off-by: Saikrishna …
> Refactor benchmark code to be a loop

- v2/conn.go
Fixes: #72
Delete TEIDSessionMap only if teid and session both match
Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>
> Fix: Delete only if teid and session both match

- v2/ies/arp.go
- v2/ies/bearer-qos.go
Fixes: #75 
1. PreemptionCapability 0 says Enabled
2. PreemptionVulnerability 0 says Enabled
3. PriorityLevel needs to be from 1 to 15 so need to right shift after masking
4. MBRForUplink starts at index 2 of the payload, else incorrectly reported 1000 as 0
Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>
> Possible bugs and deviations from wireshark

- .circleci/config.yml
- .github/workflows/go.yml
- v1/u-conn.go
Close() of the underlying connection(net.PacketConn) fails(blocks forever) when Linux Kernel GTP-U is enabled. This is just a quick workaround for that to terminate the program gracefully.
> Fix termination of U-Plane connection

- examples/mme/main.go
This will avoid race condition as pktConn used by uConn.LocalAddr() is only created in goroutine - app might fail with segfault due to null ptr dereference (which regularly happens on my machine)
> Replaced addr with sibling which is guaranteed to exist

- .gitignore
- examples/sgw/main.go
- examples/sgw/s11.go
1) There is no use case for cancelable context in test app ( closes https://github.com/wmnsk/go-gtp/issues/86 )
2) Added ports across the code since it was causing errors preventing example apps from performing expected call sequence. Now test flow works. (have not created github issue for that)
> fixed examples (no cancel for ctx + added ports for ifaces)

- .gitignore
- examples/gw-tester/enb/go.mod
- examples/gw-tester/enb/go.sum
- examples/gw-tester/mme/go.mod
- examples/gw-tester/mme/go.sum
- examples/gw-tester/pgw/go.mod
- examples/gw-tester/pgw/go.sum
- examples/gw-tester/sgw/go.mod
- examples/gw-tester/sgw/go.sum
gw-tester apps use calls from newer version of go-gtp, while configuration had old version
> gw-tester compilation fixed

- v1/constants.go
Some causes were absent in GTP v1. Added missing according to specs https://www.developingsolutions.com/reference-guides/gtp-cause-codes/
> added missing GTPv1 causes

- gtpv1/handlers.go
- gtpv1/u-conn.go
- gtpv1/u-conn_test.go
Now gtpv1.UPlaneConn responds to T-PDU with unknown TEID with Error Indication, which 3GPP tells to do.
This can be disabled by calling DisableErrorIndication(in that case the T-PDU is passed to user who calls ReadFromGTP) or replace handler with custom one using AddHandler.
> Enable Error Indication by default

- .circleci/config.yml
- .github/workflows/go.yml
- README.md
- go.mod
- go.sum
- gtpv1/errors.go
- gtpv1/u-conn.go
- gtpv2/conn.go
The current code just logs if some errors happen in `handleMessage()` and does not return error. Since the handling of error should be handled by the caller, it now returns an error.
> Return errors from handleMessage()

- gtpv1/message/header.go
- gtpv2/message/header.go
Hi @wmnsk !
We are super interested in go-gtp, but have a use-case where we decode gtp messages that are stored at the beginning of a larger buffer. Since we don't know the length of the gtp message in advance, it would be nice if go-gtp would only decode up to the length specified in the gtp header and ignore the remaining bytes. Would you be open to introducing this change?
In the current implementation, `UnmarshalBinary(...)` in header.go checks if the length specified in the header is the same as the buffer size. If not, it will just read the whole buffer:
https://github.com/wmnsk/go-gtp/blob/671898a7c7ec11da9e98c187783a374b02b0054a/gtpv1/message/header.go#L104-L108
We would like it to instead only read up to the length specified in the header (if this doesn't exceed the buffer).
In …
> Support decoding GTP messages in larger buffer

- gtpv2/ie/pco.go
Fixes #135 
Create Contents buffer before copying into it
> Fix PCOContainer UnmarshalBinary buffer allocation

- README.md
- examples/utils/mac_local_host_enabler.sh
Signed-off-by: Oriol Batalla <obatalla@fb.com>
go tsets or the MME-SGW-PGW example any ip on the localhost network 127.0.0.x  On MacOs those ip are disabled and they have to be manually enabled
This PR adds a script script to enable all 255 IPs for testing. Also it modifies the main README so other people is aware of that.
Please suggest other location for the script if that is not the correct one
Test on MacOs after running that script and go test
```
╭─ ~/testgit/go-gtp | on go-gtp_add_close_packet_channel_to_close_func *1 ?3                                                                                                                                                                 ✔ | at minikube ○ | at 17:57:03
╰─ go test  ./...
ok  	github.com/wmnsk/go-gtp	(cached)
? …
```
> Script to enable interfaces for testing on MacOs

- gtpv2/ie/cause.go
- gtpv2/ie/ie.go
#165
```go
c := v2ie.NewCause(gtpv2.CauseAPNCongestion, 0, 0, 0, v2ie.New(v2ie.AccessPointName, 0, nil))
fmt.Println(c)
fmt.Println(c.OffendingIE())
```
```
{Cause: {Type: 2, Length: 6, Instance: 0x0, Payload: []byte{0x71, 0x0, 0x47, 0x0, 0x0, 0x0}}}
{AccessPointName: {Type: 71, Length: 0, Instance: 0x0, Payload: []byte{}}} <nil>
```
> Add OffendingIE parser

- gtpv0/ie/ie.go
- gtpv1/ie/ie.go
- gtpv2/ie/ie.go
```go
c := v2ie.NewCause(gtpv2.CauseAPNCongestion, 0, 0, 0, v2ie.New(v2ie.AccessPointName, 0, nil))
fmt.Println(c.Name())
```
```
Cause
```
> Add method to retrieve the name of an IE

- gtpv0/ie/ie.go
- gtpv1/ie/ie.go
- gtpv2/ie/ie.go
Signed-off-by: Oriol Batalla <obatalla@fb.com>
For some reason when we build a message manually, some of the IEs are nil (by mistake probably). That causes the prettyprint function implemented here #164 to crash and prevents to debug the content. 
This PR will catch that nil and just print `nil` instead.
This will not prevent crashed due to nil IEs in other functions
A warning log message could be added. in case you want even more visibility in case that happens.
> Do not crash when printing the IE in case of nil IE

- gtpv2/ie/uli.go
- gtpv2/ie/uli_test.go
This fixes some bugs in the unmarshalling of the GTPv2 `UserLocationInformation` and introduces a unit test to make sure the fix works.
**Commit Msg:**
* Use correct type check in `UserLocationInformation`
* Fix segfault in `UnmarshalBinary` by creating struct before writing to it
* Fix incorrect size check in unmarshal
* Add unit test
> Fix ULI unmarshal

- gtpv1/ie/mcc-mnc.go
- gtpv1/ie/rai_test.go
- gtpv1/ie/uli_test.go
- utils/utils.go
Sorry this wasn't part of the previous PR, but I only found these bugs at a later point...
This fixes the decoding of MCC and MNC in gtp-v1 IEs. Previously, when decoding them, you would get something like "262f" as MCC, with the "f" not properly removed. The MNC decoder was also not working and didn't cover the case of 3-digit MNCs.
I replaced the `SwappedBytesToStr` call with a dedicated `DecodeM*C` call which works like the decoding of the `PLMN` in gtp-v2.
I also refactored the `PLMN` decoder a bit to make use of these new MCC/MNC decoders, so that there is no code duplication.
The unit tests I added would fail without these fixes with messages like this:
```
--- FAIL: TestNewUserLocationInformationWithCGI (0.00s)
--- FAIL: TestNewUserLocationInformationWithCGI/Test_NewUserLocationInfo …
```
> Fix gtp-v1 MCC/MNC decoding

- gtpv1/ie/imei.go
- gtpv1/ie/imei_test.go
Found another one 😉 😃
This fixes the decoding of the IMEISV IE in gtp-v1. The decoding was correct if it only contained a 15 digit IMEI, but cut off the last digit if it contained a 16 digit IMEISV.
I took the code from the MEI implementation in gtp-v2.
Without the fix, the new unit test fails with:
```
--- FAIL: TestIE_IMEISV (0.00s)
--- FAIL: TestIE_IMEISV/Encode/Decode_IMEISV (0.00s)
imei_test.go:24: wrong IMEISV, got: 123456789012345
FAIL
```
**Commit Msg:**
* Add AUT
* No longer cut off the last digit of an IMEISV
> Fix IMEISV decoding in gtp-v1

- gtpv2/ie/tft.go
Signed-off-by: Oriol Batalla <obatalla@fb.com>
Function SingleRemotePort included a wrong flag pointing to the Local port instead of Remote. This PR fixes that.
Hey @wmnsk, it would be awesome if you could provide a new tag for this fix. Thanks!
> Fixed wrong flag on SingleRemotePort function

- gtpv1/message/header.go
Make header parse next extension header type
- Add NextExtensionHeaderType field in header
- Parse NextExtensionHeaderType in UnmarshalBinary if E flag is set
- Set some method to access NextExtensionHeaderType aside for the future
> Make header parse next extension header type

- go.mod
- gtpv1/tunnel_linux.go
- gtpv1/u-conn.go
Be able to set DSCP field is required to honor PFCP's Transport Level Marking IE.
As stated in 29.281 section 4.4.1:
```
The DSCP marking as defined by IETF RFC 2474 [26] shall be set:
- based on the QCI, and optionally the ARP priority level, of the associated EPS bearer, as described in
clause 4.7.3 of 3GPP TS 23.401 [5];
- based on the 5QI and ARP of the associated 5G QoS Flow, as described in clause 5.7.1.6 and clause 5.7.1.7 of
3GPP TS 23.501 [28].
```
> Add methods in gtpv1 to set TOS / Traffic Class

- gtpv1/message/end-marker.go
- gtpv1/message/end-marker_test.go
- gtpv1/message/header.go
- gtpv1/message/message.go
with the fix for parsing messages without sequence number.
ref. #207
> Add GTPv1 EndMarker

- .github/workflows/golangci-lint.yml
- gtpv1/logger.go
- gtpv1/tunnel_linux.go
- gtpv2/conn.go
- gtpv2/ie/ip-addr.go
- gtpv2/ie/ip-addr_test.go
- gtpv2/ie/pco.go
- gtpv2/logger.go
If request contains PDNType ipv46(this means that PAA contains two addresses at the same time), there is a need to check the IP addresses. By default IP() return ipv4 address. IPv6() was updated and now return ipv6 address or err if address not present.
> Update IPv6() for PDNAddressAllocation

- gtpv1/message/extension-header.go
- gtpv1/message/header.go
- gtpv1/message/header_test.go
This PR fixes two issues related to decoding gtpv1 headers that contain inconsistent/corrupted data. It also adds unit tests to check that these headers are handled correctly. Each fix has its own commit.
Sending a packet with the extension header flag set, but without the actual extension header data, would panic with an "index out of range" error. Running the new tests without the fix would give:
<details>
<summary>Panic + Stacktrace</summary>
```
$ go test gtpv1/message/header_test.go
--- FAIL: TestHeaderErrorDetection (0.00s)
--- FAIL: TestHeaderErrorDetection/ExtFlagSetButMissingExt (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 56 [running]:
testing.tRunner.func1.2({0x53e680, …
```
> Bugfix: Do not panic when decoding corrupted headers

- gtpv2/conn.go
Make the sequence number counter wrap around to zero on reaching `0x800000` instead of `0x1000000`.  The explanation why this value should be used can be found in 3GPP TS 29.274, section 7.6 ("Reliable Delivery of Signalling Messages"), where it is mentioned that sequence numbers with their most significant bit set to 1 should be used only for Command messages and for requests which were triggered by Command messages, as well as for Triggered Reply messages, and *not* for requests which were not triggered by a Command message (i.e. Initial Request messages).  It is therefore assumed that if the sequence number counter is initialized with zero, it is supposed to be used when sending Initial Request messages only.  That's why its value becoming `0x800000` (and being incremented further) …
> [gtpv2] Fix the overflow value for the sequence number (#265)

- gtpv1/u-conn.go
In my situation, I have two goroutines: one uses `UPlaneConn.ListenAndServe` to receive packets, and the other uses `UPlaneConn.WriteTo` to send packets. It reports a race condition warning when I execute the Go program with the `-race` option.
```
func (u *UPlaneConn) ListenAndServe(ctx context.Context) error {
if u.pktConn == nil {
var err error
u.mu.Lock()
u.pktConn, err = newPktConn(u.laddr)   // <- race here
u.mu.Unlock()
if err != nil {
return err
}
}
return u.listenAndServe(ctx)
}
```
```
func (u *UPlaneConn) WriteTo(p []byte, addr net.Addr) (n int, err error) {
return u.pktConn.WriteToWithDSCPECN(p, addr, 0)  // <- race here
}
```
> fix: add lock at WriteTo
