wmnsk/go-gtp

examples/mme/mock.go
examples/pgw/pgw.go
examples/sgw/s11.go
v2/conn.go

Add session overriding feature in examples.
Now subscribers with the same IMSI will no longer exist.

Session override

---

examples/mme/main.go
examples/mme/mock.go
examples/sgw/main.go
examples/sgw/s11.go
examples/sgw/s5.go
v2/bearer.go
v2/conn.go
v2/errors.go
v2/network_test.go
v2/session.go

Follow TS 29.274 7.6 Reliable Delivery of Signalling Messages

Fix sequence number handling

---

v2/conn.go
v2/session.go

Lock strictly to avoid data race.

Fix concurrent handling of Conn and Session

---

examples/sgw/s11.go

Fixed wrong IP address given as a U-Plane address.

Fix U-Plane addr in example/sgw

---

v2/conn.go
v2/helpers_test.go

Fix the deadlock in GetIMSIByTEID and add some tests.

Fix GetIMSIByTEID() and add tests for helper funcs

---

v1/u-conn.go

By avoiding `Decode()` the performance is improved by 4.5%.

Performance improvement in GTPv1-U

---

README.md
v2/README.md
v2/messages/message.go
v2/messages/release-access-bearers-req.go
v2/messages/release-access-bearers-req_test.go
v2/messages/release-access-bearers-res.go
v2/messages/release-access-bearers-res_test.go

Add GTPv2 ReleaseAccessBearers

---

README.md
v2/README.md
v2/messages/message.go
v2/messages/stop-paging-indication.go
v2/messages/stop-paging-indication_test.go

Add GTPv2 Stop Paging Indication

---

README.md
v2/README.md
v2/messages/message.go
v2/messages/modify-access-bearers-req.go
v2/messages/modify-access-bearers-req_test.go
v2/messages/modify-access-bearers-res.go
v2/messages/modify-access-bearers-res_test.go

Add GTPv2 Modify Access Bearers

---

examples/mme/mme.go
examples/mme/mock.go
examples/pgw/pgw.go
examples/sgw/main.go
examples/sgw/s11.go
examples/sgw/s5.go
v1/errors.go
v1/handlers.go
v2/conn.go
v2/errors.go
v2/handlers.go
v2/network_test.go
v2/session.go

Updated names to follow conventions: https://github.com/golang/go/wiki/Errors#naming

Update custom error naming

---

.github/workflows/go.yml

Since I don't have plan to fix codes for windows soon, I just removed CI for Windows.

Remove CI with Windows temporarily

---

v1/u-conn.go
v2/conn.go

Fixed a bug when `Close` is called: `closeCh` is closed twice when the Conn is created with `Dial`, which caused panic.

Fix the way closing Conn

---

gtpv1/ie/end-user-address.go
gtpv1/ie/gsn-address.go
gtpv1/ie/ip.go
gtpv1/ie/lac.go
gtpv1/ie/mcc-mnc.go
gtpv1/ie/rac.go
gtpv1/ie/uli.go

_This doesn't contain any breaking changes._

Add user-friendly APIs for gtpv1/ie

---

README.md
gtpv2/README.md
gtpv2/ie/ie_test.go
gtpv2/message/delete-pdn-connection-set-req.go
gtpv2/message/delete-pdn-connection-set-req_test.go
gtpv2/message/delete-pdn-connection-set-res.go
gtpv2/message/delete-pdn-connection-set-res_test.go
gtpv2/message/detach-acknowledge.go
gtpv2/message/detach-acknowledge_test.go
gtpv2/message/detach-notification.go
gtpv2/message/detach-notification_test.go
gtpv2/message/message.go
gtpv2/message/pgw-restart-acknowledge.go
gtpv2/message/pgw-restart-notification-acknowledge_test.go
gtpv2/message/pgw-restart-notification.go
gtpv2/message/pgw-restart-notification_test.go
gtpv2/message/update-pdn-connection-set-req.go
gtpv2/message/update-pdn-connection-set-req_test.go
gtpv2/message/update-pdn-connection-set-res.go
gtpv2/message/update-pdn-connection-set-res_test.go

Added some GTPv2 messages that are used in abnormal cases.

Add some GTPv2 messages

---

gtpv2/README.md
gtpv2/ie/ie.go
gtpv2/message/context-res.go
gtpv2/message/create-bearer-res.go
gtpv2/message/create-session-res.go
gtpv2/message/delete-bearer-command.go
gtpv2/message/echo-req.go
gtpv2/message/echo-res.go
gtpv2/message/modify-access-bearers-res.go
gtpv2/message/release-access-bearers-res.go

* Added new IE types
* Added modified IEs in some messages (incl. fix of mistakes)

Update GTPv2 messages w/ Rel.16

---

gtpv2/conn.go
gtpv2/conn_test.go

Signed-off-by: Oriol Batalla <obatalla@fb.com>
This PR exposes `conn.Listen` and `conn.Serv` so client can be initialized in two steps
1- create listener
2- run the serve method
The reason to expose that is `ListenAndServe` function is normally run on a go routine in parallel. If we use the client too quick, the listener may not be initialized yet and it will panic.  Having the `Listen` and `Serve` method exposed allows us to separate the initialization of the client from the execution of the gtp server.
This PR also modifies the `setup` function at `conn_test.go` to use this two step process instead of a 1 second wait. 
`ListenAndServe` can still be used as it was (with the panic issue in case of using the client too soon after init)

Expose separatley Listen and Server on gtpv2.conn 

---

gtpv0/ie/ie.go
gtpv0/message/message.go
gtpv1/ie/ie.go
gtpv1/message/message.go
gtpv2/message/message.go

cf. #161, #163
See [this Gist](https://gist.github.com/wmnsk/f5f049ad5655584853c3762403486316) for how it looks like.
~_WIP: I'll add the name of IE in String() in v1 and v0._~ DONE.

Implement Prettifiers

---

gtpv1/README.md
gtpv1/ie/apn-restriction.go
gtpv1/ie/extension-header-type-list.go
gtpv1/ie/ie_test.go
gtpv1/message/errors.go
gtpv1/message/extension-header.go
gtpv1/message/header.go
gtpv1/message/header_test.go
gtpv1/message/message.go
gtpv1/message/supported-extension-header-notification.go
gtpv1/message/supported-extension-header-notification_test.go

This should work but to be confirmed with fresher brain tomorrow :zzz:

[gtpv1] ExtensionHeader (and N-PDU Number) support

---

gtpv2/README.md
gtpv2/message/message.go
gtpv2/message/resume-acknowledge.go
gtpv2/message/resume-acknowledge_test.go
gtpv2/message/resume-notification.go
gtpv2/message/resume-notification_test.go
gtpv2/message/suspend-acknowledge.go
gtpv2/message/suspend-acknowledge_test.go
gtpv2/message/suspend-notification.go
gtpv2/message/suspend-notification_test.go

Greetings,
This is to solve [Issue 200](https://github.com/wmnsk/go-gtp/issues/200)
bengt

Add support for suspend/resume notification/ack

---

gtpv2/message/change-notification-req.go
gtpv2/message/change-notification-req_test.go
gtpv2/message/change-notification-res.go
gtpv2/message/change-notification-res_test.go
gtpv2/message/message.go

As part of this pull request, Change Notification Req/Resp messages and unit tests for them were added.

Adding GTPv2 messages 38/39

---

gtpv2/message/create-session-req.go

Fix typos in CSR

---

.gitignore
gtp_fuzz_test.go
gtpv0/ie/ie_fuzz_test.go
gtpv0/message/header.go
gtpv0/message/message.go
gtpv0/message/message_fuzz_test.go
gtpv1/gtpv1_fuzz_test.go
gtpv1/ie/ie.go
gtpv1/ie/ie_fuzz_test.go
gtpv1/message/header_test.go
gtpv1/message/message.go
gtpv1/message/message_fuzz_test.go
gtpv2/conn.go
gtpv2/ie/ie_fuzz_test.go
gtpv2/message/message_fuzz_test.go

fixes https://github.com/wmnsk/go-gtp/issues/236

Introduce fuzzing and fix some crashing issues

---

gtpv1/ie/uli.go
gtpv1/ie/uli_test.go

[gtpv1] Fix 3-digit MNC handling in ULI

---

gtpv1/README.md
gtpv1/ie/extended-common-flags-ii.go
gtpv1/ie/extended-common-flags.go
gtpv1/message/create-pdp-context-res.go
gtpv2/ie/indication.go

* fix HasUASI
* Implemented Extended Common Flags and Flags II

Implement Extended Common Flags and Extended Common Flags II
